eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
server:
  port: 8003
  tomcat:
    uri-encoding: UTF-8


spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: acct-service
  redis:
    database: 0
    host: 192.168.23.128
    port: ${redisport:6379}
    password: ${redispwd}
    pool:
      max-active: 300
      max-wait: 10000
      max-idle: 100
      min-idle: 0
      timeout: 0
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 5
    validationQuery: SELECT 1 FROM DUAL
    initialSize: 5
    maxWait: 60000
    filters: stat,wall,log4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.23.128:${mysqlport}/${dbttname}?useUnicode=true&characterEncoding=utf-8
    maxPoolPreparedStatementPerConnectionSize: 20
    password: ${mysqlpwd}
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20
    username: ${dbttuser}

#============== kafka ===================
kafka:
  consumer:
    zookeeper:
      connect: 192.168.23.128:2181
    servers: 192.168.23.128:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: test
    group:
      id: notifyBusinessStatus
    concurrency: 10

  producer:
    zookeeper:
      connect: 192.168.23.128:2181
    servers: 192.168.23.128:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960