server:
  port: 8008
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: debug

spring:
  profiles:
    active: share
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: boot-service
  redis:
    database: 0
    host: localhost
    port: 6379
#    password: hc12345678
    pool:
      max-active: 300
      max-wait: 3000
      max-idle: 50
      min-idle: 20
      timeout: 0
  activiti:
    database-schema-update: false

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000

#============== kafka ===================
kafka:
  consumer:
    zookeeper:
      connect: 47.113.205.244:2181    #dev.zk.java110.com:2181
    servers: 47.113.205.244:9092     #dev.kafka.java110.com:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: test
    group:
      id: communityBusinessStatus
    concurrency: 10

  producer:
    zookeeper:
      connect: 47.113.205.244:2181   #dev.zk.java110.com:2181
    servers: 47.113.205.244:9092    #dev.kafka.java110.com:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960