eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
server:
  port: 8008
  tomcat:
    uri-encoding: UTF-8

spring:
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: api-service
  redis:
    database: 0
    host: 192.168.23.128
    port: 6379
    password:
    pool:
      max-active: 300
      max-wait: 10000
      max-idle: 100
      min-idle: 0
      timeout: 0



feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000


#============== kafka ===================
kafka:
  consumer:
    zookeeper:
      connect: 192.168.23.128:2181
    servers: 192.168.23.128:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: test
    group:
      id: -1  # -1 表示自己生成 走广播模式
    concurrency: 10

  producer:
    zookeeper:
      connect: 192.168.23.128:2181
    servers: 192.168.23.128:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960

logging:
  level:
    com.java110.core.smo: debug